# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "tuesday"
    labels:
      - "dependencies"

  - package-ecosystem: "pipenv"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "tuesday"
    labels:
      - "dependencies"

  - package-ecosystem: "terraform"
    directory: "/operations/app/terraform"
    schedule:
      interval: "weekly"
      day: "tuesday"
    labels:
      - "dependencies"
