---
schema:
  Patient:
    Identifier:
      fhir_path: /resources/resource/entry/Patient/identifier
      include_nulls: false
      include_unknowns: false
      selection_criteria: first
      new_name: identifier
    First Name:
      fhir_path: /resources/resource/entry/Patient/name/given/first
      include_nulls: false
      include_unknowns: false
      selection_criteria: first
      new_name: first_name
    Last Name:
      fhir_path: /resources/resource/entry/Patient/name/family
      include_nulls: false
      include_unknowns: false
      selection_criteria: first
      new_name: last_name